baseURL = "https://tylucie.fr/"
languageCode = "en-us"
title = "ğŸ¡ Ty Lucie"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  footer = 'ğŸŒ² 48Â°24â€™41.2â€N 3Â°46â€™15.2â€W - '

[params.social]
  email = "yannick@tylucie.fr"
  domain = "tylucie.fr"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "IMJQP"

[permalinks]
  posts = "/:slug"
  pages = "/:slug"
